package api

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
)

// NewRouter constructs the public HTTP router with default middleware
// and all currently-mounted endpoints. Future milestones add the
// auth-protected routes (§2.3+).
//
// db may be nil in dev/test setups without DATABASE_URL; HealthHandler
// then reports the database as "disabled".
func NewRouter(db Pinger) http.Handler {
	r := chi.NewRouter()
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)
	r.Use(middleware.Recoverer)
	r.Use(echoRequestID)

	r.Method(http.MethodGet, "/healthz", HealthHandler(db))
	return r
}

// echoRequestID copies the request ID generated by chi's RequestID
// middleware onto the response so clients can correlate logs.
func echoRequestID(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if id := middleware.GetReqID(r.Context()); id != "" {
			w.Header().Set("X-Request-Id", id)
		}
		next.ServeHTTP(w, r)
	})
}
