package api

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"

	"github.com/nigel4321/macos-screentime/backend/internal/auth"
)

// Deps bundles the dependencies the API layer needs to mount its
// routes. A nil DB or nil auth dependencies disable the routes that
// require them, which keeps tests and dev-without-Postgres flows
// simple.
//
// IMPORTANT: assign DB only with a non-nil concrete pointer. A typed
// nil (e.g. `(*pgxpool.Pool)(nil)`) stored here becomes a non-nil
// interface and crashes the /healthz Ping. Either leave DB as the zero
// value or assign through `if pool != nil { d.DB = pool }`.
type Deps struct {
	DB             Pinger
	Store          *auth.Store
	AppleVerifier  *auth.IDTokenVerifier
	GoogleVerifier *auth.IDTokenVerifier
	JWTSigner      *auth.Signer
	JWTVerifier    *auth.Verifier
	// DeviceTokenMinter overrides the default crypto/rand-backed token
	// generator. Leave nil in production; tests inject a deterministic
	// minter when they need to assert exact response payloads.
	DeviceTokenMinter DeviceTokenMinter
	// UsageStore backs /v1/usage:batchUpload. nil disables the route.
	UsageStore UsageStore
	// PolicyStore backs GET/PUT /v1/policy. nil disables the routes.
	PolicyStore PolicyStore
}

// NewRouter constructs the public HTTP router with default middleware
// and all currently-mounted endpoints. Auth- and pairing-protected
// routes are mounted only when the relevant Deps fields are non-nil.
func NewRouter(d Deps) http.Handler {
	r := chi.NewRouter()
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)
	r.Use(middleware.Recoverer)
	r.Use(echoRequestID)

	r.Method(http.MethodGet, "/healthz", HealthHandler(d.DB))

	if d.Store != nil && d.JWTSigner != nil {
		if d.AppleVerifier != nil {
			r.Method(http.MethodPost, "/v1/auth/apple",
				IdentityExchangeHandler(d.AppleVerifier, d.Store, d.JWTSigner))
		}
		if d.GoogleVerifier != nil {
			r.Method(http.MethodPost, "/v1/auth/google",
				IdentityExchangeHandler(d.GoogleVerifier, d.Store, d.JWTSigner))
		}

		if d.JWTVerifier != nil {
			minter := d.DeviceTokenMinter
			if minter == nil {
				minter = DefaultDeviceTokenMinter()
			}
			r.Group(func(r chi.Router) {
				r.Use(auth.Authenticator(d.JWTVerifier, d.Store))
				r.Method(http.MethodPost, "/v1/account:pair-init",
					PairInitHandler(d.Store))
				r.Method(http.MethodPost, "/v1/account:pair-complete",
					PairCompleteHandler(d.Store, d.JWTSigner))
				r.Method(http.MethodPost, "/v1/devices/register",
					DevicesRegisterHandler(d.Store, minter))
				r.Method(http.MethodGet, "/v1/devices",
					DevicesListHandler(d.Store))

				if d.PolicyStore != nil {
					r.Method(http.MethodGet, "/v1/policy/current",
						PolicyCurrentHandler(d.PolicyStore))
					r.Method(http.MethodPut, "/v1/policy",
						PolicyPutHandler(d.PolicyStore))
				}

				if d.UsageStore != nil {
					// Summary spans all of the account's devices, so it
					// only needs Authenticator — no X-Device-Token.
					r.Method(http.MethodGet, "/v1/usage:summary",
						UsageSummaryHandler(d.UsageStore))
				}

				// Sub-group for routes that additionally require a
				// resolved device — DeviceContext reads X-Device-Token
				// and stashes the device id on the request context.
				if d.UsageStore != nil {
					r.Group(func(r chi.Router) {
						r.Use(auth.DeviceContext(d.Store))
						r.Method(http.MethodPost, "/v1/usage:batchUpload",
							BatchUploadHandler(d.UsageStore))
					})
				}
			})
		}
	}

	return r
}

// echoRequestID copies the request ID generated by chi's RequestID
// middleware onto the response so clients can correlate logs.
func echoRequestID(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if id := middleware.GetReqID(r.Context()); id != "" {
			w.Header().Set("X-Request-Id", id)
		}
		next.ServeHTTP(w, r)
	})
}
